language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install poetry pytest black

install:
  - poetry install --extras=docs

script:
  - black --check -q .
  - poetry run python -m pytest
