[tool.poetry]
name = "litebird_sim"
version = "0.1.0"
description = "Simulation tools for the LiteBIRD experiment"
authors = ["Maurizio Tomasi <maurizio.tomasi@unimi.it>"]

[tool.poetry.dependencies]
python = "^3.7"
numba = "^0.47.0"
numpy = "^1.18"
astropy = "^4.0"
tomlkit = "^0.5.8"
sphinx = {version = "^2.3", optional = true}
sphinx_rtd_theme = {version = "^0.4.3", optional = true}
jupyter = {version = "^1.0", extras = ["jupyter"]}
[tool.poetry.extras]
docs = ["sphinx", "sphinx_rtd_theme"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
